apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-comm-api
spec:
  selector:
    matchLabels:
      app: x-comm-api
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: x-comm-api
        tier: backend
        track: stable
    spec:
      containers:
        - name: x-comm-api
          image: "ecimionatto/x-comm-api"
          imagePullPolicy: Never
          env:
            - name: MONGODB_HOST
              value: mongodb
          ports:
            - name: http
              containerPort: 8080