apiVersion: v1
kind: Service
metadata:
  name: x-comm-dashboard
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: x-comm-dashboard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-comm-dashboard
spec:
  selector:
    matchLabels:
      app: hello
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
        track: stable
    spec:
      containers:
        - name: x-comm-dashboard
          image: "ecimionatto/x-comm-dashboard"
          imagePullPolicy: Never