apiVersion: v1
kind: Service
metadata:
  name: x-comm
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: x-comm

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-comm
spec:
  selector:
    matchLabels:
      app: x-comm
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: x-comm
        track: stable
    spec:
      containers:
        - name: x-comm-api
          image: "ecimionatto/x-comm-api"
          env:
            - name: MONGODB_HOST
              value: mongodb
          ports:
            - name: http
              containerPort: 8080
        - name: x-comm-dashboard
          image: "ecimionatto/x-comm-dashboard"
          ports:
            - name: http
              containerPort: 3000
